name = "pip"
description = "pip package manager hooks"
entry_point = "main.ts"

[permissions]
run = ["/bin", "/usr/bin", "~/.pyenv"]
write = ["~/Library/Caches/pip", "~/.cache", "~/.local/lib", "/tmp"]
read = ["~/Library/Caches/pip", "~/.cache", "~/.local/lib", "/tmp", "/etc/passwd", "/etc/apache2/mime.types"]
net = true
unsandboxed_run = ["pip"]
